parameters:
#    digital_rep_api.example.class: DigitalRep\APIBundle\Example

services:
#    digital_rep_api.example:
#        class: %digital_rep_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
