parameters:
#    digital_rep_users.example.class: DigitalRep\UsersBundle\Example

services:
#    digital_rep_users.example:
#        class: %digital_rep_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
